name: "My Composite Action"
description: "A reusable composite action that setup .NET."

inputs:
  dotnet-version:
    description: "The .NET version to use"
    default: "8.0.x"
    required: false



runs:
  using: "composite"
  steps:
    - name: Set up .NET
      id: setup-dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}  
    - name: Set result output
      id: set-result
      run: echo "result=Success" >> $GITHUB_OUTPUT
      shell: bash
      