name: "My Composite Action"
description: "A reusable composite action that checks out code and sets up Node.js"

inputs:
  dotnet-version:
    description: "The .NET version to use"
    default: "8.0.x"
    required: false

outputs:
  script-result:
    description: "Result from installer"
    value: ${{ steps.run-script.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Set up .NET
      id: setup-dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}  
    - name: Set result output
      id: set-result
      run: |
        if [ "${{ steps.setup-dotnet.outcome }}" = "success" ]; then
          echo "result=Success" >> $GITHUB_OUTPUT
        else
          echo "result=Failed" >> $GITHUB_OUTPUT
        fi
      shell: bash
      