name: "My Composite Action"
description: "A reusable composite action that checks out code and sets up Node.js"

inputs:
  dotnet-version:
    description: "The .NET version to use"
    default: "8.0.x"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}  
      